doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        dbname: FirstApp
        host: localhost
        port: 3306
        user: root
        password: null
        driver: mysql
        
